### ISSUE TITLE
Provide(advise) with Ami example

### ISSUE THREAD

**Issue by andrusstrockiy** [rdegges/pyst2#15]
He first of all thank you for you hard work to keep on track the pyst2 module.
Second could you advise what appropriate method should do the job of reading all events from asterisk ami interface.

For example when I make login according your example:
<pre>
            manager.connect('asterisk.sip.net')
            manager.login('test', 'test')
            resp = manager.status()
</pre>
All I need just to read all events from the asterisk ami output and act accordingly.

**Comment by rdegges** [comment]
Hey there, this is a better question for StackOverflow. I only use the issue tracker here to track bugs / etc.
