### ISSUE TITLE
bug in agi.py

### ISSUE THREAD

**Issue by sancho2934489** [rdegges/pyst2#21]
I worked agi.py, was as follows:
def __init__(self, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr):
        self._got_sighup = False
        signal.signal(signal.SIGHUP, self._handle_sighup)  # handle SIGHUP
        self.stderr.write('ARGS: ')
        self.stderr.write(str(sys.argv))
        self.stderr.write('\n')
        self.stdin = stdin
        self.stdout = stdout
        self.stderr = stderr
        self.env = {}
        self._get_agi_env()

Error:
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    agi = AGI()
  File "/usr/local/lib/python2.7/dist-packages/pyst2-0.4.8-py2.7.egg/asterisk/agi.py", line 91, in __init__
    self.stderr.write('ARGS: ')

I did so:
def __init__(self,stdin=sys.stdin,stdout=sys.stdout,stderr=sys.stderr):
        self.stdin=stdin
        self.stdout=stdout
        self.stderr=stderr
        self._got_sighup = False
        signal.signal(signal.SIGHUP, self._handle_sighup)  # handle SIGHUP
        self.stderr.write('ARGS: ')
        self.stderr.write(str(sys.argv))
        self.stderr.write('\n')
        self.env = {}
        self._get_agi_env()
It began to work.

**Comment by rdegges** [comment]
Thanks for brining this to my attention! Just fixed this, and I'm cutting a new release now. Please update from PyPI =)

**Comment by rdegges** [comment]
I think that's part of the AGI protocol, no? It's honestly been a few years since I've worked with this, so my memory is really fuzzy =/ If you can remove the STDERR writing and just rely on STDOUT, that'd be ideal. I'm not a fan of arbitrary log statements without using a proper logger with different log levels / etc.

**Comment by tuxpowered** [comment]
AGI protocol is just stdin stdout. Stderr, should not be sent to asterisk
but rather to the active shell.

I would have to test just to make sure, and yes if I did do logging it
would be with standard logging library and set to different levels. Info,
warn, critical, debug.

It just occurred to me that maybe the agitb module requires the stderr. I
am not sure how that code work...
